services:
  laravel.test:
    image: laravelsail/php84-composer:latest
    command: >
      sh -c "
      if ! id -u sail > /dev/null 2>&1; then
        adduser -u 1337 -D -s /bin/sh sail &&
        echo 'sail ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
      fi &&
      php-fpm"
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ..:/var/www/html
    networks:
      - sail
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "laravel"
    ports:
      - "3306:3306"
    volumes:
      - sail-mysql:/var/lib/mysql
    networks:
      - sail

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - sail

networks:
  sail:

volumes:
  sail-mysql:
